iitkgp:
	sudo gcc -o tr tr.c
	sudo ./tr iitkgp.ac.in

local:
	sudo gcc -o tr tr.c
	sudo ./tr localhost

moodle:
	sudo gcc -o tr tr.c
	sudo ./tr kgpmoodlenew.iitkgp.ac.in

csemoodle:
	sudo gcc -o tr tr.c
	sudo ./tr moodlecse.iitkgp.ac.in

gitu:
	gcc -o ass ass6.c 
	sudo ./ass iitkgp.ac.in

default:
	traceroute iitkgp.ac.in

push:
	git add -A
	git commit -m "GG <3, always"
	git push

clean:
	sudo rm -f *.o localhost tr ass
